// Generated by gencpp from file jethexa_controller_interfaces/JointCommand.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_JOINTCOMMAND_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_JOINTCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct JointCommand_
{
  typedef JointCommand_<ContainerAllocator> Type;

  JointCommand_()
    : target()
    , duration(0.0)  {
      target.assign(0.0);
  }
  JointCommand_(const ContainerAllocator& _alloc)
    : target()
    , duration(0.0)  {
  (void)_alloc;
      target.assign(0.0);
  }



   typedef boost::array<float, 18>  _target_type;
  _target_type target;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> const> ConstPtr;

}; // struct JointCommand_

typedef ::jethexa_controller_interfaces::JointCommand_<std::allocator<void> > JointCommand;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::JointCommand > JointCommandPtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::JointCommand const> JointCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10ef9426383df380694d1e1ce8eec8d2";
  }

  static const char* value(const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10ef9426383df380ULL;
  static const uint64_t static_value2 = 0x694d1e1ce8eec8d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/JointCommand";
  }

  static const char* value(const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[18] target\n"
"float32 duration\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::JointCommand_<ContainerAllocator>& v)
  {
    s << indent << "target[]" << std::endl;
    for (size_t i = 0; i < v.target.size(); ++i)
    {
      s << indent << "  target[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.target[i]);
    }
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_JOINTCOMMAND_H
